# Simple workflow for deploying static content to GitHub Pages
name: Deploy Mosaic Component

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Modules
        run: npm ci
      - name: Build Pages
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-site
          path: ./dist/

  # Deployment job
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy_pages.outputs.deploy_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: built-site
          path: ./dist/
      - name: Deploy to GitHub Pages
        id: deploy_pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./dist/
